### ISSUE TITLE
Error after login (missing localization default)

### ISSUE THREAD

**Issue by Baioretto** [Katharsas/GMM#137]
java.lang.RuntimeException: freemarker.core._TemplateModelException: Java method "org.springframework.web.servlet.support.RequestContext.getMessage(String)" threw an exception when invoked on org.springframework.web.servlet.support.RequestContext object "org.springframework.web.servlet.support.RequestContext@295fea18"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${springMacroRequestContext.getMessag...  [in template "spring.ftl" in macro "message" at line 28, column 22]
	- Reached through: @s.message taskForm.type.getTypeKey()  [in template "all_taskForm.html.ftl" at line 12, column 25]
----

	at gmm.web.FtlRenderer.renderTemplate(FtlRenderer.java:125)

	at gmm.web.FtlRenderer.renderTemplate(FtlRenderer.java:69)

	at gmm.web.FtlTemplateService.insertFtl(FtlTemplateService.java:87)

	at gmm.web.controller.TaskController.renderTaskForm(TaskController.java:214)

	at gmm.web.controller.TaskController$$FastClassBySpringCGLIB$$4c2bd232.invoke(<generated>)

	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)

	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:67)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)

	at gmm.web.controller.TaskController$$EnhancerBySpringCGLIB$$818dad75.renderTaskForm(<generated>)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)

	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)

	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)

	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)

	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)

	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)

	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:502)

	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:352)

	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)

	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)

	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:164)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:170)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)

	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)

	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)

	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)

	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225)

	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)

	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)

	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

	at gmm.BlockUntilReadyFilter.doFilter(BlockUntilReadyFilter.java:45)

	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)

	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)

	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)

	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)

	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.base/java.lang.Thread.run(Thread.java:833)

Caused by: freemarker.core._TemplateModelException: Java method "org.springframework.web.servlet.support.RequestContext.getMessage(String)" threw an exception when invoked on org.springframework.web.servlet.support.RequestContext object "org.springframework.web.servlet.support.RequestContext@295fea18"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${springMacroRequestContext.getMessag...  [in template "spring.ftl" in macro "message" at line 28, column 22]
	- Reached through: @s.message taskForm.type.getTypeKey()  [in template "all_taskForm.html.ftl" at line 12, column 25]
----

	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:292)

	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:264)

	at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:66)

	at freemarker.core.MethodCall._eval(MethodCall.java:62)

	at freemarker.core.Expression.eval(Expression.java:101)

	at freemarker.core.BuiltInsForOutputFormatRelated$AbstractConverterBI.calculateResult(BuiltInsForOutputFormatRelated.java:50)

	at freemarker.core.MarkupOutputFormatBoundBuiltIn._eval(MarkupOutputFormatBoundBuiltIn.java:40)

	at freemarker.core.Expression.eval(Expression.java:101)

	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)

	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)

	at freemarker.core.Environment.visit(Environment.java:383)

	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:889)

	at freemarker.core.Environment.invokeMacro(Environment.java:825)

	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)

	at freemarker.core.Environment.visit(Environment.java:347)

	at freemarker.core.Environment.visit(Environment.java:353)

	at freemarker.core.Environment.process(Environment.java:326)

	at freemarker.template.Template.process(Template.java:383)

	at gmm.web.FtlRenderer.renderTemplate(FtlRenderer.java:123)

	... 105 more

Caused by: org.springframework.context.NoSuchMessageException: No message found under code 'tasks.type' for locale 'pl'.

	at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:161)

	at org.springframework.context.support.DelegatingMessageSource.getMessage(DelegatingMessageSource.java:73)

	at org.springframework.context.support.AbstractApplicationContext.getMessage(AbstractApplicationContext.java:1383)

	at org.springframework.web.servlet.support.RequestContext.getMessage(RequestContext.java:703)

	at org.springframework.web.servlet.support.RequestContext.getMessage(RequestContext.java:669)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1552)

	at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:56)

	at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:51)

	at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:62)

	... 121 more

???all_template.reload???

**Comment by Katharsas** [comment]
@Baioretto Baioretto
I cannot reproduce this problem neither in Chrome nor Firefox, even when setting preferred language to polish in the browser settings. What browser and what language settings do you use?

**Comment by Baioretto** [comment]
Polish language and no matter which browser i will use


pon., 3 kwi 2023 o 22:12 Jan ***@***.***> napisał(a):

**Comment by Katharsas** [comment]
I still don't have this problem. I set my Firefox settings to polish:
![image](https://user-images.githubusercontent.com/1922573/230224996-1c47039a-2c4f-4a90-a374-4156d3130e91.png)

And GMM fallback to english seems to be working fine.

Unless you tell me exactly what settings in what browser you are using, including every single language settings with screenshots i cannot help you. And also tell me exactly what you click in GMM to make it happen.

**Comment by Baioretto** [comment]
i redone all once again, i changed language to english and it works. i
don't know what was wrong but we can close this issue.

czw., 6 kwi 2023 o 00:26 Jan ***@***.***> napisał(a):
